linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - typecheck
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

run:
  tests: true
  timeout: 5m

issues:
  max-same-issues: 10
  max-issues-per-linter: 0
  exclude-use-default: false
  exclude-dirs:
    - "internal/shared/repositories"
