// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repositories

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/Toppira-Official/Reminder_Server/internal/shared/entities"
)

func newReminder(db *gorm.DB, opts ...gen.DOOption) reminder {
	_reminder := reminder{}

	_reminder.reminderDo.UseDB(db, opts...)
	_reminder.reminderDo.UseModel(&entities.Reminder{})

	tableName := _reminder.reminderDo.TableName()
	_reminder.ALL = field.NewAsterisk(tableName)
	_reminder.BaseID = field.NewUint(tableName, "id")
	_reminder.BaseCreatedAt = field.NewTime(tableName, "created_at")
	_reminder.BaseUpdatedAt = field.NewTime(tableName, "updated_at")
	_reminder.Title = field.NewString(tableName, "title")
	_reminder.Description = field.NewString(tableName, "description")
	_reminder.Status = field.NewString(tableName, "status")
	_reminder.ReminderTimes = field.NewField(tableName, "reminder_times")
	_reminder.ScheduledAt = field.NewTime(tableName, "scheduled_at")
	_reminder.Priority = field.NewString(tableName, "priority")
	_reminder.UserID = field.NewUint(tableName, "user_id")
	_reminder.User = reminderBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "entities.User"),
		Reminders: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("User.Reminders", "entities.Reminder"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Reminders.User", "entities.User"),
			},
		},
	}

	_reminder.fillFieldMap()

	return _reminder
}

type reminder struct {
	reminderDo reminderDo

	ALL           field.Asterisk
	BaseID        field.Uint
	BaseCreatedAt field.Time
	BaseUpdatedAt field.Time
	Title         field.String
	Description   field.String
	Status        field.String
	ReminderTimes field.Field
	ScheduledAt   field.Time
	Priority      field.String
	UserID        field.Uint
	User          reminderBelongsToUser

	fieldMap map[string]field.Expr
}

func (r reminder) Table(newTableName string) *reminder {
	r.reminderDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r reminder) As(alias string) *reminder {
	r.reminderDo.DO = *(r.reminderDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *reminder) updateTableName(table string) *reminder {
	r.ALL = field.NewAsterisk(table)
	r.BaseID = field.NewUint(table, "id")
	r.BaseCreatedAt = field.NewTime(table, "created_at")
	r.BaseUpdatedAt = field.NewTime(table, "updated_at")
	r.Title = field.NewString(table, "title")
	r.Description = field.NewString(table, "description")
	r.Status = field.NewString(table, "status")
	r.ReminderTimes = field.NewField(table, "reminder_times")
	r.ScheduledAt = field.NewTime(table, "scheduled_at")
	r.Priority = field.NewString(table, "priority")
	r.UserID = field.NewUint(table, "user_id")

	r.fillFieldMap()

	return r
}

func (r *reminder) WithContext(ctx context.Context) IReminderDo { return r.reminderDo.WithContext(ctx) }

func (r reminder) TableName() string { return r.reminderDo.TableName() }

func (r reminder) Alias() string { return r.reminderDo.Alias() }

func (r reminder) Columns(cols ...field.Expr) gen.Columns { return r.reminderDo.Columns(cols...) }

func (r *reminder) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *reminder) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 11)
	r.fieldMap["id"] = r.BaseID
	r.fieldMap["created_at"] = r.BaseCreatedAt
	r.fieldMap["updated_at"] = r.BaseUpdatedAt
	r.fieldMap["title"] = r.Title
	r.fieldMap["description"] = r.Description
	r.fieldMap["status"] = r.Status
	r.fieldMap["reminder_times"] = r.ReminderTimes
	r.fieldMap["scheduled_at"] = r.ScheduledAt
	r.fieldMap["priority"] = r.Priority
	r.fieldMap["user_id"] = r.UserID

}

func (r reminder) clone(db *gorm.DB) reminder {
	r.reminderDo.ReplaceConnPool(db.Statement.ConnPool)
	r.User.db = db.Session(&gorm.Session{Initialized: true})
	r.User.db.Statement.ConnPool = db.Statement.ConnPool
	return r
}

func (r reminder) replaceDB(db *gorm.DB) reminder {
	r.reminderDo.ReplaceDB(db)
	r.User.db = db.Session(&gorm.Session{})
	return r
}

type reminderBelongsToUser struct {
	db *gorm.DB

	field.RelationField

	Reminders struct {
		field.RelationField
		User struct {
			field.RelationField
		}
	}
}

func (a reminderBelongsToUser) Where(conds ...field.Expr) *reminderBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a reminderBelongsToUser) WithContext(ctx context.Context) *reminderBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a reminderBelongsToUser) Session(session *gorm.Session) *reminderBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a reminderBelongsToUser) Model(m *entities.Reminder) *reminderBelongsToUserTx {
	return &reminderBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

func (a reminderBelongsToUser) Unscoped() *reminderBelongsToUser {
	a.db = a.db.Unscoped()
	return &a
}

type reminderBelongsToUserTx struct{ tx *gorm.Association }

func (a reminderBelongsToUserTx) Find() (result *entities.User, err error) {
	return result, a.tx.Find(&result)
}

func (a reminderBelongsToUserTx) Append(values ...*entities.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a reminderBelongsToUserTx) Replace(values ...*entities.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a reminderBelongsToUserTx) Delete(values ...*entities.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a reminderBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a reminderBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

func (a reminderBelongsToUserTx) Unscoped() *reminderBelongsToUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type reminderDo struct{ gen.DO }

type IReminderDo interface {
	gen.SubQuery
	Debug() IReminderDo
	WithContext(ctx context.Context) IReminderDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IReminderDo
	WriteDB() IReminderDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IReminderDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IReminderDo
	Not(conds ...gen.Condition) IReminderDo
	Or(conds ...gen.Condition) IReminderDo
	Select(conds ...field.Expr) IReminderDo
	Where(conds ...gen.Condition) IReminderDo
	Order(conds ...field.Expr) IReminderDo
	Distinct(cols ...field.Expr) IReminderDo
	Omit(cols ...field.Expr) IReminderDo
	Join(table schema.Tabler, on ...field.Expr) IReminderDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IReminderDo
	RightJoin(table schema.Tabler, on ...field.Expr) IReminderDo
	Group(cols ...field.Expr) IReminderDo
	Having(conds ...gen.Condition) IReminderDo
	Limit(limit int) IReminderDo
	Offset(offset int) IReminderDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IReminderDo
	Unscoped() IReminderDo
	Create(values ...*entities.Reminder) error
	CreateInBatches(values []*entities.Reminder, batchSize int) error
	Save(values ...*entities.Reminder) error
	First() (*entities.Reminder, error)
	Take() (*entities.Reminder, error)
	Last() (*entities.Reminder, error)
	Find() ([]*entities.Reminder, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entities.Reminder, err error)
	FindInBatches(result *[]*entities.Reminder, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entities.Reminder) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IReminderDo
	Assign(attrs ...field.AssignExpr) IReminderDo
	Joins(fields ...field.RelationField) IReminderDo
	Preload(fields ...field.RelationField) IReminderDo
	FirstOrInit() (*entities.Reminder, error)
	FirstOrCreate() (*entities.Reminder, error)
	FindByPage(offset int, limit int) (result []*entities.Reminder, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IReminderDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r reminderDo) Debug() IReminderDo {
	return r.withDO(r.DO.Debug())
}

func (r reminderDo) WithContext(ctx context.Context) IReminderDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r reminderDo) ReadDB() IReminderDo {
	return r.Clauses(dbresolver.Read)
}

func (r reminderDo) WriteDB() IReminderDo {
	return r.Clauses(dbresolver.Write)
}

func (r reminderDo) Session(config *gorm.Session) IReminderDo {
	return r.withDO(r.DO.Session(config))
}

func (r reminderDo) Clauses(conds ...clause.Expression) IReminderDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r reminderDo) Returning(value interface{}, columns ...string) IReminderDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r reminderDo) Not(conds ...gen.Condition) IReminderDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r reminderDo) Or(conds ...gen.Condition) IReminderDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r reminderDo) Select(conds ...field.Expr) IReminderDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r reminderDo) Where(conds ...gen.Condition) IReminderDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r reminderDo) Order(conds ...field.Expr) IReminderDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r reminderDo) Distinct(cols ...field.Expr) IReminderDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r reminderDo) Omit(cols ...field.Expr) IReminderDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r reminderDo) Join(table schema.Tabler, on ...field.Expr) IReminderDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r reminderDo) LeftJoin(table schema.Tabler, on ...field.Expr) IReminderDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r reminderDo) RightJoin(table schema.Tabler, on ...field.Expr) IReminderDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r reminderDo) Group(cols ...field.Expr) IReminderDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r reminderDo) Having(conds ...gen.Condition) IReminderDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r reminderDo) Limit(limit int) IReminderDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r reminderDo) Offset(offset int) IReminderDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r reminderDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IReminderDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r reminderDo) Unscoped() IReminderDo {
	return r.withDO(r.DO.Unscoped())
}

func (r reminderDo) Create(values ...*entities.Reminder) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r reminderDo) CreateInBatches(values []*entities.Reminder, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r reminderDo) Save(values ...*entities.Reminder) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r reminderDo) First() (*entities.Reminder, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entities.Reminder), nil
	}
}

func (r reminderDo) Take() (*entities.Reminder, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entities.Reminder), nil
	}
}

func (r reminderDo) Last() (*entities.Reminder, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entities.Reminder), nil
	}
}

func (r reminderDo) Find() ([]*entities.Reminder, error) {
	result, err := r.DO.Find()
	return result.([]*entities.Reminder), err
}

func (r reminderDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entities.Reminder, err error) {
	buf := make([]*entities.Reminder, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r reminderDo) FindInBatches(result *[]*entities.Reminder, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r reminderDo) Attrs(attrs ...field.AssignExpr) IReminderDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r reminderDo) Assign(attrs ...field.AssignExpr) IReminderDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r reminderDo) Joins(fields ...field.RelationField) IReminderDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r reminderDo) Preload(fields ...field.RelationField) IReminderDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r reminderDo) FirstOrInit() (*entities.Reminder, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entities.Reminder), nil
	}
}

func (r reminderDo) FirstOrCreate() (*entities.Reminder, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entities.Reminder), nil
	}
}

func (r reminderDo) FindByPage(offset int, limit int) (result []*entities.Reminder, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r reminderDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r reminderDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r reminderDo) Delete(models ...*entities.Reminder) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *reminderDo) withDO(do gen.Dao) *reminderDo {
	r.DO = *do.(*gen.DO)
	return r
}
