// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Ali Moradi",
            "email": "AliMoradi0Business@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/sign-up-with-user-password": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "sign up with email and password",
                "parameters": [
                    {
                        "description": "Sign Up Input",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_auth_handler.SignUpWithEmailPasswordInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Toppira-Official_backend_internal_shared_dto.HttpOutputDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Toppira-Official_backend_internal_shared_errors.ClientError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Toppira-Official_backend_internal_shared_errors.ClientError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_Toppira-Official_backend_internal_shared_dto.HttpOutputDto": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "github_com_Toppira-Official_backend_internal_shared_errors.ClientError": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_Toppira-Official_backend_internal_shared_errors.ErrCode"
                }
            }
        },
        "github_com_Toppira-Official_backend_internal_shared_errors.ErrCode": {
            "type": "string",
            "enum": [
                "SERVER_INTERNAL_ERROR",
                "SERVER_NOT_RESPONDING",
                "USER_INVALID_DATA",
                "USER_ALREADY_EXISTS",
                "USER_NOT_FOUND",
                "AUTH_INVALID_TOKEN",
                "AUTH_EXPIRED_TOKEN"
            ],
            "x-enum-varnames": [
                "ErrServerInternalError",
                "ErrServerNotResponding",
                "ErrUserInvalidData",
                "ErrUserAlreadyExists",
                "ErrUserNotFound",
                "ErrAuthInvalidToken",
                "ErrAuthExpiredToken"
            ]
        },
        "internal_modules_auth_handler.SignUpWithEmailPasswordInput": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 8
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Toppira APIs",
	Description:      "Toppira APIs Documents.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
